
### GETTING ALL USERS
get http://localhost:9000/user

### creating user

POST http://localhost:9000/user/create
Content-Type: application/json

{
    "email":"Guru01@gmail.com",
    "password": "guru001"
}
### user login

POST http://localhost:9000/user/login
Content-Type: application/json

{
    "email":"Guru@gmail.com",
    "password": "guru001"
}


###  todo/create
POST http://localhost:9000/todo/create
Content-Type: application/json
Authorization: Bearer "token  ----"

{
    "title":"todo 0005"
}

### geting all  todos
get http://localhost:9000/todo/alllist

### autherized todos 
get http://localhost:9000/todo/list
Content-Type: application/json
Authorization: Bearer "token----------"